image: python

stages:
- test

# python2:
#   image: python:2.7
#   stage: test
#   script: tox -e py27

# python34:
#   image: python:3.4
#   stage: test
#   script: tox -e py34

# python35:
#   image: python:3.5
#   stage: test
#   script: tox -e py35

# python36:
#   image: python:3.6
#   stage: test
#   script: tox -e py36

flake8:
  image: python:3.6
  stage: test
  script: tox -e flake8

readme:
  image: python:3.6
  stage: test
  script: tox -e docs
